---
title: "day3_prac4_5"
format: html
---

## Question 4: Plot the function

```{r setup, message=FALSE, warning=FALSE}
x <- seq(-2, 2, length.out = 1000)
plot(x, sin(x), type = "l", lwd = 2,
     xlab = "x", ylab = "sin(x)",
     main = "Sine function on [-2, 2]")
grid()
```

## Question 5: QQ-Plot

```{r}

#Generate 1000 values from a  t distribution with 1 degree of freedom.
set.seed(123)
n <- 1000
x <- rt(n, df = 1)    


# Construct theoretical normal quantiles
m <- 100000
z <- sort(rnorm(m))    # large normal sample

# plotting positions
p <- (1:n - 0.5) / n

# approximate theoretical quantiles
theoretical <- z[ceiling(p * m)]
# Sample quantiles
sample_q <- sort(x)

# 95% QQ-plot envelopes
# standard normal density (manual)
phi <- function(z) {
  (1 / sqrt(2 * pi)) * exp(-z^2 / 2)
}

se <- sqrt(p * (1 - p)) / (sqrt(n) * phi(theoretical))
z_alpha <- 1.96

upper <- theoretical + z_alpha * se
lower <- theoretical - z_alpha * se

# Manual QQ-plot with envelopes
plot(theoretical, sample_q,
     pch = 20,
     cex = 0.6,
     xlab = "Theoretical Normal Quantiles",
     ylab = "Sample Quantiles",
     ylim = c(-5, 5),
     main = "Normal QQ-Plot with 95% Envelopes")

lines(theoretical, upper, col = "red", lty = 2)
lines(theoretical, lower, col = "red", lty = 2)
abline(0, 1, col = "blue")

# Check using car::qqPlot
library(car)
qqPlot(x, envelope = 0.95, ylim = c(-5, 5))



```
